# Generated by Django 5.2.7 on 2025-10-29 09:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camp',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('camp_type', models.CharField(choices=[('shelter', 'Shelter'), ('medical', 'Medical'), ('distribution', 'Distribution'), ('evacuation', 'Evacuation'), ('rescue', 'Rescue Center')], max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('capacity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)])),
                ('contact_person', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{9,15}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('status', models.CharField(choices=[('active', 'Active'), ('full', 'Full'), ('closed', 'Closed'), ('maintenance', 'Under Maintenance')], default='active', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('disasters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasters.disasters')),
            ],
            options={
                'db_table': 'camps',
                'indexes': [models.Index(fields=['camp_type', 'status'], name='camps_camp_ty_90f78e_idx'), models.Index(fields=['disasters'], name='camps_disaste_aff75f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('camp_type__in', ['shelter', 'medical', 'distribution', 'evacuation', 'rescue'])), name='valid_camp_type'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'full', 'closed', 'maintenance'])), name='valid_camp_status'), models.CheckConstraint(condition=models.Q(('capacity__gte', 1), ('capacity__lte', 10000)), name='valid_capacity_range')],
                'unique_together': {('name', 'disasters')},
            },
        ),
    ]
