# Generated by Django 5.2.7 on 2025-12-05 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camp',
            name='coverage_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='camp',
            name='population_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20000)]),
        ),
        migrations.AddField(
            model_name='camp',
            name='service_area_description',
            field=models.TextField(blank=True),
        ),
    ]
