# Generated by Django 5.2.7 on 2025-10-29 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disasters', '0001_initial'),
        ('operations', '0001_initial'),
        ('relief', '0001_initial'),
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationacknowledgment',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationacknowledgment',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.donation'),
        ),
        migrations.AddField(
            model_name='donationitem',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.donation'),
        ),
        migrations.AddField(
            model_name='donationitem',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relief.resource'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='disasters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasters.disasters'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='victim',
            field=models.ForeignKey(limit_choices_to={'role': 'victim'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='help_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.helprequest'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='volunteer',
            field=models.ForeignKey(limit_choices_to={'role': 'volunteer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transport',
            name='assigned_to_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelters.camp'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor_type', 'donation_date'], name='donations_donor_t_2df2ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(condition=models.Q(('donor_type__in', ['individual', 'organization'])), name='valid_donor_type'),
        ),
        migrations.AddIndex(
            model_name='donationitem',
            index=models.Index(fields=['resource'], name='donation_it_resourc_1c5e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['status', 'requested_at'], name='help_reques_status_27880d_idx'),
        ),
        migrations.AddConstraint(
            model_name='helprequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'in_progress', 'resolved', 'cancelled'])), name='valid_help_status'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['status', 'assigned_at'], name='task_assign_status_9dbf20_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['assigned', 'in_progress', 'completed', 'cancelled'])), name='valid_task_status'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['transport_type', 'status'], name='transports_transpo_6dc26e_idx'),
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.CheckConstraint(condition=models.Q(('transport_type__in', ['truck', 'van', 'boat', 'helicopter', 'other'])), name='valid_transport_type'),
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['available', 'in_use', 'maintenance', 'unavailable'])), name='valid_transport_status'),
        ),
    ]
