# Generated by Django 4.2.27 on 2026-01-09 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0001_initial'),
        ('relief', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttrip',
            name='assigned_resources',
            field=models.ManyToManyField(blank=True, related_name='transport_trips', to='relief.resource'),
        ),
    ]
