# Generated by Django 5.2.7 on 2025-12-05 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_initial'),
        ('relief', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name='HelpRequestStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('help_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='operations.helprequest')),
            ],
            options={
                'db_table': 'help_request_status_history',
                'indexes': [models.Index(fields=['help_request'], name='help_reques_help_re_5e54e6_idx'), models.Index(fields=['new_status', 'changed_at'], name='help_reques_new_sta_548b73_idx')],
            },
        ),
        migrations.CreateModel(
            name='TaskAssignmentStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='operations.taskassignment')),
            ],
            options={
                'db_table': 'task_assignment_status_history',
                'indexes': [models.Index(fields=['task'], name='task_assign_task_id_83821d_idx'), models.Index(fields=['new_status', 'changed_at'], name='task_assign_new_sta_ceb029_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransportTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('en_route', 'En Route'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('cargo_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_resources', models.ManyToManyField(blank=True, related_name='transport_trips', to='relief.resource')),
                ('assigned_volunteers', models.ManyToManyField(blank=True, limit_choices_to={'role': 'volunteer'}, related_name='transport_trips', to=settings.AUTH_USER_MODEL)),
                ('transport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='operations.transport')),
            ],
            options={
                'db_table': 'transport_trips',
                'indexes': [models.Index(fields=['transport'], name='transport_t_transpo_60b557_idx'), models.Index(fields=['status', 'departure_time'], name='transport_t_status_08a6df_idx')],
            },
        ),
    ]
