# Generated by Django 5.2.7 on 2026-01-09 16:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0002_disasters_affected_population_estimate_and_more'),
        ('operations', '0002_initial'),
        ('relief', '0002_initial'),
        ('shelters', '0002_camp_coverage_radius_km_camp_population_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpRequestStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'help_request_status_history',
            },
        ),
        migrations.CreateModel(
            name='TaskAssignmentStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('assigned', 'Assigned'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'task_assignment_status_history',
            },
        ),
        migrations.CreateModel(
            name='TransportTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('departure_time', models.DateTimeField()),
                ('arrival_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('en_route', 'En Route'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20)),
                ('cargo_description', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'transport_trips',
            },
        ),
        migrations.AddField(
            model_name='helprequest',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, help_text='Volunteer who is helping with this request', limit_choices_to={'role': 'volunteer'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_help_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='transport',
            name='current_location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['latitude', 'longitude'], name='help_reques_latitud_c0aa2e_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['assigned_volunteer', 'status'], name='help_reques_assigne_51f776_idx'),
        ),
        migrations.AddField(
            model_name='helprequeststatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helprequeststatushistory',
            name='help_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='operations.helprequest'),
        ),
        migrations.AddField(
            model_name='taskassignmentstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignmentstatushistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='operations.taskassignment'),
        ),
        migrations.AddField(
            model_name='transporttrip',
            name='assigned_resources',
            field=models.ManyToManyField(blank=True, related_name='transport_trips', to='relief.resource'),
        ),
        migrations.AddField(
            model_name='transporttrip',
            name='assigned_volunteers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'volunteer'}, related_name='transport_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transporttrip',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='operations.transport'),
        ),
        migrations.AddIndex(
            model_name='helprequeststatushistory',
            index=models.Index(fields=['help_request'], name='help_reques_help_re_5e54e6_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequeststatushistory',
            index=models.Index(fields=['new_status', 'changed_at'], name='help_reques_new_sta_548b73_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignmentstatushistory',
            index=models.Index(fields=['task'], name='task_assign_task_id_83821d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignmentstatushistory',
            index=models.Index(fields=['new_status', 'changed_at'], name='task_assign_new_sta_ceb029_idx'),
        ),
        migrations.AddIndex(
            model_name='transporttrip',
            index=models.Index(fields=['transport'], name='transport_t_transpo_60b557_idx'),
        ),
        migrations.AddIndex(
            model_name='transporttrip',
            index=models.Index(fields=['status', 'departure_time'], name='transport_t_status_08a6df_idx'),
        ),
    ]
