# Generated by Django 4.2.27 on 2026-01-09 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0002_initial'),
        ('shelters', '0001_initial'),
        ('relief', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transporttrip',
            name='assigned_volunteers',
            field=models.ManyToManyField(blank=True, limit_choices_to={'role': 'volunteer'}, related_name='transport_trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='transporttrip',
            name='transport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='operations.transport'),
        ),
        migrations.AddField(
            model_name='transport',
            name='assigned_to_camp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shelters.camp'),
        ),
        migrations.AddField(
            model_name='taskassignmentstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskassignmentstatushistory',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='operations.taskassignment'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='help_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operations.helprequest'),
        ),
        migrations.AddField(
            model_name='taskassignment',
            name='volunteer',
            field=models.ForeignKey(limit_choices_to={'role': 'volunteer'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helprequeststatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='helprequeststatushistory',
            name='help_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='operations.helprequest'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='disasters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasters.disasters'),
        ),
        migrations.AddField(
            model_name='helprequest',
            name='victim',
            field=models.ForeignKey(limit_choices_to={'role': 'victim'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationitem',
            name='donation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='operations.donation'),
        ),
        migrations.AddField(
            model_name='donationitem',
            name='resource',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='relief.resource'),
        ),
        migrations.AddField(
            model_name='donationacknowledgment',
            name='acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donationacknowledgment',
            name='donation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='operations.donation'),
        ),
        migrations.AddField(
            model_name='donation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='transporttrip',
            index=models.Index(fields=['transport'], name='transport_t_transpo_60b557_idx'),
        ),
        migrations.AddIndex(
            model_name='transporttrip',
            index=models.Index(fields=['status', 'departure_time'], name='transport_t_status_08a6df_idx'),
        ),
        migrations.AddIndex(
            model_name='transport',
            index=models.Index(fields=['transport_type', 'status'], name='transports_transpo_6dc26e_idx'),
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.CheckConstraint(check=models.Q(('transport_type__in', ['truck', 'van', 'boat', 'helicopter', 'other'])), name='valid_transport_type'),
        ),
        migrations.AddConstraint(
            model_name='transport',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['available', 'in_use', 'maintenance', 'unavailable'])), name='valid_transport_status'),
        ),
        migrations.AddIndex(
            model_name='taskassignmentstatushistory',
            index=models.Index(fields=['task'], name='task_assign_task_id_83821d_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignmentstatushistory',
            index=models.Index(fields=['new_status', 'changed_at'], name='task_assign_new_sta_ceb029_idx'),
        ),
        migrations.AddIndex(
            model_name='taskassignment',
            index=models.Index(fields=['status', 'assigned_at'], name='task_assign_status_9dbf20_idx'),
        ),
        migrations.AddConstraint(
            model_name='taskassignment',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['assigned', 'in_progress', 'completed', 'cancelled'])), name='valid_task_status'),
        ),
        migrations.AddIndex(
            model_name='helprequeststatushistory',
            index=models.Index(fields=['help_request'], name='help_reques_help_re_5e54e6_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequeststatushistory',
            index=models.Index(fields=['new_status', 'changed_at'], name='help_reques_new_sta_548b73_idx'),
        ),
        migrations.AddIndex(
            model_name='helprequest',
            index=models.Index(fields=['status', 'requested_at'], name='help_reques_status_27880d_idx'),
        ),
        migrations.AddConstraint(
            model_name='helprequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'in_progress', 'resolved', 'cancelled'])), name='valid_help_status'),
        ),
        migrations.AddIndex(
            model_name='donationitem',
            index=models.Index(fields=['resource'], name='donation_it_resourc_1c5e7a_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor_type', 'donation_date'], name='donations_donor_t_2df2ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(check=models.Q(('donor_type__in', ['individual', 'organization'])), name='valid_donor_type'),
        ),
    ]
