# Generated by Django 5.2.7 on 2026-01-09 13:28
# Syntax fixed for Django 5.0.x compatibility

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_transport_current_location_helprequeststatushistory_and_more'),
        ('shelters', '0002_camp_coverage_radius_km_camp_population_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='donation',
            name='donations_donor_t_2df2ca_idx',
        ),
        migrations.AddField(
            model_name='donation',
            name='camp',
            field=models.ForeignKey(
                to='shelters.camp',
                related_name='donations',
                null=True,
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
            ),
        ),
        migrations.AddField(
            model_name='donation',
            name='status',
            field=models.CharField(
                max_length=20,
                default='pending',
                choices=[
                    ('pending', 'Pending'),
                    ('accepted', 'Accepted'),
                    ('rejected', 'Rejected'),
                ],
            ),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['camp', 'status'], name='donations_camp_id_b086b6_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['created_by', 'donation_date'], name='donations_created_8e6974_idx'),
        ),
        migrations.AddConstraint(
            model_name='donation',
            constraint=models.CheckConstraint(
                check=models.Q(
                    status__in=['pending', 'accepted', 'rejected']
                ),
                name='valid_donation_status',
            ),
        ),
    ]
