# Generated by Django 5.2.7 on 2026-01-09 14:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_remove_donation_donations_donor_t_2df2ca_idx_and_more'),
        ('shelters', '0002_camp_coverage_radius_km_camp_population_capacity_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor_type', 'donation_date'], name='donations_donor_t_2df2ca_idx'),
        ),
    ]
