# Generated by Django 5.0.14 on 2026-01-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_donation_status_admin_message'),
        ('operations', '0005_donation_donations_donor_t_2df2ca_idx'),
    ]

    operations = [
    ]
