# Generated by Django 5.2.7 on 2026-01-09 16:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='current_location',
            field=models.CharField(blank=True, help_text='Current location address', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AddField(
            model_name='user',
            name='location_updated_at',
            field=models.DateTimeField(blank=True, help_text='When location was last updated', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate', max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)]),
        ),
        migrations.AddField(
            model_name='victim',
            name='emergency_supplies_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='is_high_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='victim',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='victim',
            name='special_needs',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('camp_admin', 'Camp Admin'), ('volunteer', 'Volunteer'), ('victim', 'Victim'), ('donor', 'Donor')], default='volunteer', max_length=20),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['latitude', 'longitude'], name='users_latitud_0614c3_idx'),
        ),
    ]
