# Generated by Django 5.2.7 on 2025-11-01 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('camp_admin', 'Camp Admin'), ('volunteer', 'Volunteer'), ('victim', 'Victim'), ('donor', 'Donor')], default='volunteer', max_length=20),
        ),
    ]
