# Generated by Django 5.2.7 on 2025-12-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='victim',
            name='emergency_supplies_needed',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='is_high_risk',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='victim',
            name='medical_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='victim',
            name='priority_level',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10),
        ),
        migrations.AddField(
            model_name='victim',
            name='special_needs',
            field=models.TextField(blank=True),
        ),
    ]
