# Generated by Django 4.2.27 on 2026-01-09 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disasters',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('disaster_type', models.CharField(choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('hurricane', 'Hurricane'), ('tsunami', 'Tsunami'), ('fire', 'Fire'), ('landslide', 'Landslide'), ('drought', 'Drought'), ('other', 'Other')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('contained', 'Contained'), ('resolved', 'Resolved')], default='active', max_length=10)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('description', models.TextField()),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('estimated_damage', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('affected_areas', models.TextField(blank=True)),
                ('affected_population_estimate', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('impact_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('impact_area_description', models.TextField(blank=True)),
                ('geojson_boundary', models.TextField(blank=True, help_text='Optional GeoJSON polygon for mapping.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'disasters',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['disaster_type', 'status'], name='disasters_disaste_551bb9_idx'), models.Index(fields=['severity'], name='disasters_severit_e71f5e_idx'), models.Index(fields=['start_date'], name='disasters_start_d_54bc7f_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='disasters',
            constraint=models.CheckConstraint(check=models.Q(('disaster_type__in', ['earthquake', 'flood', 'hurricane', 'tsunami', 'fire', 'landslide', 'drought', 'other'])), name='valid_disaster_type'),
        ),
        migrations.AddConstraint(
            model_name='disasters',
            constraint=models.CheckConstraint(check=models.Q(('severity__in', ['low', 'medium', 'high', 'critical'])), name='valid_severity_level'),
        ),
        migrations.AddConstraint(
            model_name='disasters',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'contained', 'resolved'])), name='valid_status'),
        ),
        migrations.AddConstraint(
            model_name='disasters',
            constraint=models.CheckConstraint(check=models.Q(('end_date__isnull', True), ('end_date__gt', models.F('start_date')), _connector='OR'), name='valid_date_range'),
        ),
    ]
