# Generated by Django 5.2.7 on 2025-12-05 16:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disasters',
            name='affected_population_estimate',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='disasters',
            name='geojson_boundary',
            field=models.TextField(blank=True, help_text='Optional GeoJSON polygon for mapping.'),
        ),
        migrations.AddField(
            model_name='disasters',
            name='impact_area_description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='disasters',
            name='impact_radius_km',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='disasters',
            name='disaster_type',
            field=models.CharField(choices=[('earthquake', 'Earthquake'), ('flood', 'Flood'), ('hurricane', 'Hurricane'), ('tsunami', 'Tsunami'), ('fire', 'Fire'), ('landslide', 'Landslide'), ('drought', 'Drought'), ('other', 'Other')], max_length=20),
        ),
    ]
