# Generated by Django 5.2.7 on 2025-10-29 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='active', max_length=10)),
                ('Disasters', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasters.disasters')),
            ],
            options={
                'db_table': 'alerts',
                'indexes': [models.Index(fields=['severity', 'status'], name='alerts_severit_ae6d4c_idx'), models.Index(fields=['issued_at'], name='alerts_issued__79af81_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('severity__in', ['low', 'medium', 'high', 'critical'])), name='valid_alert_severity'), models.CheckConstraint(condition=models.Q(('status__in', ['active', 'resolved', 'cancelled'])), name='valid_alert_status')],
            },
        ),
    ]
