# Generated by Django 5.2.7 on 2025-11-29 05:05

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('disasters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('weather_type', models.CharField(choices=[('hurricane', 'Hurricane'), ('flood', 'Flood'), ('drought', 'Drought'), ('storm', 'Storm'), ('tornado', 'Tornado'), ('heatwave', 'Heatwave'), ('coldwave', 'Coldwave'), ('tsunami', 'Tsunami'), ('other', 'Other')], max_length=20)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('extreme', 'Extreme')], default='moderate', max_length=20)),
                ('status', models.CharField(choices=[('forecast', 'Forecast'), ('active', 'Active'), ('warning', 'Warning'), ('expired', 'Expired')], default='forecast', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('forecast_date', models.DateTimeField()),
                ('expected_severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('affected_radius_km', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('wind_speed_kmh', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('rainfall_mm', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('temperature_celsius', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(-50), django.core.validators.MaxValueValidator(60)])),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('issued_by', models.ForeignKey(blank=True, limit_choices_to={'role__in': ['super_admin', 'camp_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('related_disaster', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disasters.disasters')),
            ],
            options={
                'db_table': 'weather_alerts',
                'ordering': ['-forecast_date', '-risk_level'],
                'indexes': [models.Index(fields=['weather_type', 'risk_level'], name='weather_ale_weather_c0c239_idx'), models.Index(fields=['status', 'forecast_date'], name='weather_ale_status_e85af9_idx'), models.Index(fields=['risk_level', 'status'], name='weather_ale_risk_le_33bcde_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('weather_type__in', ['hurricane', 'flood', 'drought', 'storm', 'tornado', 'heatwave', 'coldwave', 'tsunami', 'other'])), name='valid_weather_type'), models.CheckConstraint(condition=models.Q(('risk_level__in', ['low', 'moderate', 'high', 'extreme'])), name='valid_risk_level'), models.CheckConstraint(condition=models.Q(('status__in', ['forecast', 'active', 'warning', 'expired'])), name='valid_weather_status')],
            },
        ),
    ]
