# Generated by Django 5.2.7 on 2026-01-09 16:34
# Syntax fixed for Django 5.0.x compatibility

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
        ('disasters', '0002_disasters_affected_population_estimate_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherAlert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'weather_type',
                    models.CharField(
                        max_length=20,
                        choices=[
                            ('hurricane', 'Hurricane'),
                            ('flood', 'Flood'),
                            ('drought', 'Drought'),
                            ('storm', 'Storm'),
                            ('tornado', 'Tornado'),
                            ('heatwave', 'Heatwave'),
                            ('coldwave', 'Coldwave'),
                            ('tsunami', 'Tsunami'),
                            ('other', 'Other'),
                        ],
                    ),
                ),
                (
                    'risk_level',
                    models.CharField(
                        max_length=20,
                        default='moderate',
                        choices=[
                            ('low', 'Low'),
                            ('moderate', 'Moderate'),
                            ('high', 'High'),
                            ('extreme', 'Extreme'),
                        ],
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        max_length=20,
                        default='forecast',
                        choices=[
                            ('forecast', 'Forecast'),
                            ('active', 'Active'),
                            ('warning', 'Warning'),
                            ('expired', 'Expired'),
                        ],
                    ),
                ),
                ('location', models.CharField(max_length=255)),
                (
                    'latitude',
                    models.DecimalField(
                        max_digits=9,
                        decimal_places=6,
                        null=True,
                        blank=True,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    'longitude',
                    models.DecimalField(
                        max_digits=9,
                        decimal_places=6,
                        null=True,
                        blank=True,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('forecast_date', models.DateTimeField()),
                (
                    'expected_severity',
                    models.CharField(
                        max_length=20,
                        default='medium',
                        choices=[
                            ('low', 'Low'),
                            ('medium', 'Medium'),
                            ('high', 'High'),
                            ('critical', 'Critical'),
                        ],
                    ),
                ),
                (
                    'affected_radius_km',
                    models.DecimalField(
                        max_digits=10,
                        decimal_places=2,
                        null=True,
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'wind_speed_kmh',
                    models.DecimalField(
                        max_digits=6,
                        decimal_places=2,
                        null=True,
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'rainfall_mm',
                    models.DecimalField(
                        max_digits=8,
                        decimal_places=2,
                        null=True,
                        blank=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    'temperature_celsius',
                    models.DecimalField(
                        max_digits=5,
                        decimal_places=2,
                        null=True,
                        blank=True,
                        validators=[
                            django.core.validators.MinValueValidator(-50),
                            django.core.validators.MaxValueValidator(60),
                        ],
                    ),
                ),
                ('issued_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(null=True, blank=True)),
                (
                    'issued_by',
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        limit_choices_to={'role__in': ['super_admin', 'camp_admin']},
                    ),
                ),
                (
                    'related_disaster',
                    models.ForeignKey(
                        to='disasters.disasters',
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                    ),
                ),
            ],
            options={
                'db_table': 'weather_alerts',
                'ordering': ['-forecast_date', '-risk_level'],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlertStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'previous_status',
                    models.CharField(
                        max_length=20,
                        choices=[
                            ('forecast', 'Forecast'),
                            ('active', 'Active'),
                            ('warning', 'Warning'),
                            ('expired', 'Expired'),
                        ],
                    ),
                ),
                (
                    'new_status',
                    models.CharField(
                        max_length=20,
                        choices=[
                            ('forecast', 'Forecast'),
                            ('active', 'Active'),
                            ('warning', 'Warning'),
                            ('expired', 'Expired'),
                        ],
                    ),
                ),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                (
                    'changed_by',
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                    ),
                ),
                (
                    'weather_alert',
                    models.ForeignKey(
                        to='alerts.weatheralert',
                        related_name='status_history',
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
            ],
            options={
                'db_table': 'weather_alert_status_history',
            },
        ),
        migrations.CreateModel(
            name='AlertStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                (
                    'previous_status',
                    models.CharField(
                        max_length=10,
                        choices=[
                            ('active', 'Active'),
                            ('resolved', 'Resolved'),
                            ('cancelled', 'Cancelled'),
                        ],
                    ),
                ),
                (
                    'new_status',
                    models.CharField(
                        max_length=10,
                        choices=[
                            ('active', 'Active'),
                            ('resolved', 'Resolved'),
                            ('cancelled', 'Cancelled'),
                        ],
                    ),
                ),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                (
                    'alert',
                    models.ForeignKey(
                        to='alerts.alert',
                        related_name='status_history',
                        on_delete=django.db.models.deletion.CASCADE,
                    ),
                ),
                (
                    'changed_by',
                    models.ForeignKey(
                        to=settings.AUTH_USER_MODEL,
                        null=True,
                        blank=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                    ),
                ),
            ],
            options={
                'db_table': 'alert_status_history',
                'indexes': [
                    models.Index(fields=['alert'], name='alert_statu_alert_i_bdcbb2_idx'),
                    models.Index(fields=['new_status', 'changed_at'], name='alert_statu_new_sta_ea242e_idx'),
                ],
            },
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['weather_type', 'risk_level'], name='weather_ale_weather_c0c239_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['status', 'forecast_date'], name='weather_ale_status_e85af9_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['risk_level', 'status'], name='weather_ale_risk_le_33bcde_idx'),
        ),
        migrations.AddConstraint(
            model_name='weatheralert',
            constraint=models.CheckConstraint(
                check=models.Q(
                    weather_type__in=[
                        'hurricane',
                        'flood',
                        'drought',
                        'storm',
                        'tornado',
                        'heatwave',
                        'coldwave',
                        'tsunami',
                        'other',
                    ]
                ),
                name='valid_weather_type',
            ),
        ),
        migrations.AddConstraint(
            model_name='weatheralert',
            constraint=models.CheckConstraint(
                check=models.Q(
                    risk_level__in=['low', 'moderate', 'high', 'extreme']
                ),
                name='valid_risk_level',
            ),
        ),
        migrations.AddConstraint(
            model_name='weatheralert',
            constraint=models.CheckConstraint(
                check=models.Q(
                    status__in=['forecast', 'active', 'warning', 'expired']
                ),
                name='valid_weather_status',
            ),
        ),
        migrations.AddIndex(
            model_name='weatheralertstatushistory',
            index=models.Index(fields=['weather_alert'], name='weather_ale_weather_f5b252_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralertstatushistory',
            index=models.Index(fields=['new_status', 'changed_at'], name='weather_ale_new_sta_003166_idx'),
        ),
    ]
