# Generated by Django 4.2.27 on 2026-01-09 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alerts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('disasters', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weatheralertstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weatheralertstatushistory',
            name='weather_alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='alerts.weatheralert'),
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='issued_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['super_admin', 'camp_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='weatheralert',
            name='related_disaster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='disasters.disasters'),
        ),
        migrations.AddField(
            model_name='alertstatushistory',
            name='alert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='alerts.alert'),
        ),
        migrations.AddField(
            model_name='alertstatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='Disasters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disasters.disasters'),
        ),
        migrations.AddIndex(
            model_name='weatheralertstatushistory',
            index=models.Index(fields=['weather_alert'], name='weather_ale_weather_f5b252_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralertstatushistory',
            index=models.Index(fields=['new_status', 'changed_at'], name='weather_ale_new_sta_003166_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['weather_type', 'risk_level'], name='weather_ale_weather_c0c239_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['status', 'forecast_date'], name='weather_ale_status_e85af9_idx'),
        ),
        migrations.AddIndex(
            model_name='weatheralert',
            index=models.Index(fields=['risk_level', 'status'], name='weather_ale_risk_le_33bcde_idx'),
        ),
        migrations.AddConstraint(
            model_name='weatheralert',
            constraint=models.CheckConstraint(check=models.Q(('weather_type__in', ['hurricane', 'flood', 'drought', 'storm', 'tornado', 'heatwave', 'coldwave', 'tsunami', 'other'])), name='valid_weather_type'),
        ),
        migrations.AddConstraint(
            model_name='weatheralert',
            constraint=models.CheckConstraint(check=models.Q(('risk_level__in', ['low', 'moderate', 'high', 'extreme'])), name='valid_risk_level'),
        ),
        migrations.AddConstraint(
            model_name='weatheralert',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['forecast', 'active', 'warning', 'expired'])), name='valid_weather_status'),
        ),
        migrations.AddIndex(
            model_name='alertstatushistory',
            index=models.Index(fields=['alert'], name='alert_statu_alert_i_bdcbb2_idx'),
        ),
        migrations.AddIndex(
            model_name='alertstatushistory',
            index=models.Index(fields=['new_status', 'changed_at'], name='alert_statu_new_sta_ea242e_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['severity', 'status'], name='alerts_severit_ae6d4c_idx'),
        ),
        migrations.AddIndex(
            model_name='alert',
            index=models.Index(fields=['issued_at'], name='alerts_issued__79af81_idx'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(check=models.Q(('severity__in', ['low', 'medium', 'high', 'critical'])), name='valid_alert_severity'),
        ),
        migrations.AddConstraint(
            model_name='alert',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['active', 'resolved', 'cancelled'])), name='valid_alert_status'),
        ),
    ]
