# Generated by Django 5.2.7 on 2025-12-05 16:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_weatheralert'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=10)),
                ('new_status', models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], max_length=10)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='alerts.alert')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'alert_status_history',
                'indexes': [models.Index(fields=['alert'], name='alert_statu_alert_i_bdcbb2_idx'), models.Index(fields=['new_status', 'changed_at'], name='alert_statu_new_sta_ea242e_idx')],
            },
        ),
        migrations.CreateModel(
            name='WeatherAlertStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('forecast', 'Forecast'), ('active', 'Active'), ('warning', 'Warning'), ('expired', 'Expired')], max_length=20)),
                ('new_status', models.CharField(choices=[('forecast', 'Forecast'), ('active', 'Active'), ('warning', 'Warning'), ('expired', 'Expired')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('weather_alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='alerts.weatheralert')),
            ],
            options={
                'db_table': 'weather_alert_status_history',
                'indexes': [models.Index(fields=['weather_alert'], name='weather_ale_weather_f5b252_idx'), models.Index(fields=['new_status', 'changed_at'], name='weather_ale_new_sta_003166_idx')],
            },
        ),
    ]
