# Generated by Django 5.2.7 on 2025-10-29 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communication', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='communication',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='communication',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['sender', 'receiver'], name='communicati_sender__5ba2e8_idx'),
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['status', 'sent_at'], name='communicati_status_c1873a_idx'),
        ),
        migrations.AddConstraint(
            model_name='communication',
            constraint=models.CheckConstraint(condition=models.Q(('message_type__in', ['text', 'image', 'video', 'document'])), name='valid_message_type'),
        ),
        migrations.AddConstraint(
            model_name='communication',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['sent', 'delivered', 'read'])), name='valid_message_status'),
        ),
    ]
