# Generated by Django 5.2.7 on 2025-10-29 09:48

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField(choices=[('food', 'Food'), ('water', 'Water'), ('medical', 'Medical Supplies'), ('clothing', 'Clothing'), ('shelter', 'Shelter Materials'), ('hygiene', 'Hygiene Kits'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('box', 'Box'), ('pack', 'Pack'), ('unit', 'Unit')], max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resources',
                'indexes': [models.Index(fields=['category', 'is_active'], name='resources_categor_89e624_idx'), models.Index(fields=['is_active'], name='resources_is_acti_e1ba4f_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('category__in', ['food', 'water', 'medical', 'clothing', 'shelter', 'hygiene', 'equipment', 'other'])), name='valid_resource_category'), models.CheckConstraint(condition=models.Q(('unit__in', ['kg', 'g', 'l', 'ml', 'piece', 'box', 'pack', 'unit'])), name='valid_resource_unit')],
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity_fulfilled', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('needed_by', models.DateTimeField()),
                ('reason', models.TextField()),
                ('camp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.camp')),
            ],
            options={
                'db_table': 'resource_requests',
            },
        ),
    ]
