# Generated by Django 4.2.27 on 2026-01-09 07:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('category', models.CharField(choices=[('food', 'Food'), ('water', 'Water'), ('medical', 'Medical Supplies'), ('clothing', 'Clothing'), ('shelter', 'Shelter Materials'), ('hygiene', 'Hygiene Kits'), ('equipment', 'Equipment'), ('other', 'Other')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('unit', models.CharField(choices=[('kg', 'Kilogram'), ('g', 'Gram'), ('l', 'Liter'), ('ml', 'Milliliter'), ('piece', 'Piece'), ('box', 'Box'), ('pack', 'Pack'), ('unit', 'Unit')], max_length=10)),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('available_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resources',
            },
        ),
        migrations.CreateModel(
            name='ResourceInventoryTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('add', 'Addition'), ('remove', 'Removal'), ('adjust', 'Manual Adjustment'), ('fulfillment', 'Request Fulfillment'), ('donation', 'Donation Intake')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(-9999999999.99)])),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resource_inventory_transactions',
            },
        ),
        migrations.CreateModel(
            name='ResourceRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity_requested', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('quantity_fulfilled', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('needed_by', models.DateTimeField()),
                ('reason', models.TextField()),
            ],
            options={
                'db_table': 'resource_requests',
            },
        ),
        migrations.CreateModel(
            name='ResourceRequestStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resource_request_status_history',
            },
        ),
    ]
