# Generated by Django 4.2.27 on 2026-01-09 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('operations', '0002_initial'),
        ('relief', '0001_initial'),
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequeststatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcerequeststatushistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='relief.resourcerequest'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='camp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelters.camp'),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='requested_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['camp_admin', 'super_admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relief.resource'),
        ),
        migrations.AddField(
            model_name='resourceinventorytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceinventorytransaction',
            name='related_donation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.donationitem'),
        ),
        migrations.AddField(
            model_name='resourceinventorytransaction',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relief.resourcerequest'),
        ),
        migrations.AddField(
            model_name='resourceinventorytransaction',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='relief.resource'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['category', 'is_active'], name='resources_categor_89e624_idx'),
        ),
        migrations.AddIndex(
            model_name='resource',
            index=models.Index(fields=['is_active'], name='resources_is_acti_e1ba4f_idx'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(check=models.Q(('category__in', ['food', 'water', 'medical', 'clothing', 'shelter', 'hygiene', 'equipment', 'other'])), name='valid_resource_category'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(check=models.Q(('unit__in', ['kg', 'g', 'l', 'ml', 'piece', 'box', 'pack', 'unit'])), name='valid_resource_unit'),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(check=models.Q(('available_quantity__gte', 0), ('available_quantity__lte', models.F('total_quantity'))), name='available_not_exceed_total'),
        ),
        migrations.AddIndex(
            model_name='resourcerequeststatushistory',
            index=models.Index(fields=['request'], name='resource_re_request_488d56_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequeststatushistory',
            index=models.Index(fields=['new_status', 'changed_at'], name='resource_re_new_sta_374a30_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['camp', 'status'], name='resource_re_camp_id_ea62ea_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['priority', 'needed_by'], name='resource_re_priorit_6f4cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['status', 'request_date'], name='resource_re_status_a200b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcerequest',
            constraint=models.CheckConstraint(check=models.Q(('priority__in', ['low', 'medium', 'high', 'urgent'])), name='valid_priority_level'),
        ),
        migrations.AddConstraint(
            model_name='resourcerequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['pending', 'approved', 'rejected', 'fulfilled', 'cancelled'])), name='valid_request_status'),
        ),
        migrations.AddConstraint(
            model_name='resourcerequest',
            constraint=models.CheckConstraint(check=models.Q(('quantity_fulfilled__lte', models.F('quantity_requested'))), name='fulfillment_not_exceed_request'),
        ),
        migrations.AddConstraint(
            model_name='resourcerequest',
            constraint=models.CheckConstraint(check=models.Q(('needed_by__gt', models.F('request_date'))), name='needed_by_after_request_date'),
        ),
        migrations.AddIndex(
            model_name='resourceinventorytransaction',
            index=models.Index(fields=['resource', 'transaction_type'], name='resource_in_resourc_f05a35_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceinventorytransaction',
            index=models.Index(fields=['created_at'], name='resource_in_created_94ebb5_idx'),
        ),
    ]
