# Generated by Django 5.2.7 on 2025-10-29 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('relief', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcerequest',
            name='requested_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['camp_admin', 'super_admin']}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcerequest',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='relief.resource'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['camp', 'status'], name='resource_re_camp_id_ea62ea_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['priority', 'needed_by'], name='resource_re_priorit_6f4cd4_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequest',
            index=models.Index(fields=['status', 'request_date'], name='resource_re_status_a200b4_idx'),
        ),
        migrations.AddConstraint(
            model_name='resourcerequest',
            constraint=models.CheckConstraint(condition=models.Q(('priority__in', ['low', 'medium', 'high', 'urgent'])), name='valid_priority_level'),
        ),
        migrations.AddConstraint(
            model_name='resourcerequest',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['pending', 'approved', 'rejected', 'fulfilled', 'cancelled'])), name='valid_request_status'),
        ),
        migrations.AddConstraint(
            model_name='resourcerequest',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_fulfilled__lte', models.F('quantity_requested'))), name='fulfillment_not_exceed_request'),
        ),
        migrations.AddConstraint(
            model_name='resourcerequest',
            constraint=models.CheckConstraint(condition=models.Q(('needed_by__gt', models.F('request_date'))), name='needed_by_after_request_date'),
        ),
    ]
