# Generated by Django 5.2.7 on 2025-12-05 16:03

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0003_transport_current_location_helprequeststatushistory_and_more'),
        ('relief', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceInventoryTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('add', 'Addition'), ('remove', 'Removal'), ('adjust', 'Manual Adjustment'), ('fulfillment', 'Request Fulfillment'), ('donation', 'Donation Intake')], max_length=20)),
                ('quantity_delta', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(-9999999999.99)])),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resource_inventory_transactions',
            },
        ),
        migrations.CreateModel(
            name='ResourceRequestStatusHistory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], max_length=20)),
                ('new_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('fulfilled', 'Fulfilled'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'resource_request_status_history',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='available_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='resource',
            name='total_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddConstraint(
            model_name='resource',
            constraint=models.CheckConstraint(condition=models.Q(('available_quantity__gte', 0), ('available_quantity__lte', models.F('total_quantity'))), name='available_not_exceed_total'),
        ),
        migrations.AddField(
            model_name='resourceinventorytransaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourceinventorytransaction',
            name='related_donation_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='operations.donationitem'),
        ),
        migrations.AddField(
            model_name='resourceinventorytransaction',
            name='related_request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='relief.resourcerequest'),
        ),
        migrations.AddField(
            model_name='resourceinventorytransaction',
            name='resource',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_transactions', to='relief.resource'),
        ),
        migrations.AddField(
            model_name='resourcerequeststatushistory',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='resourcerequeststatushistory',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='relief.resourcerequest'),
        ),
        migrations.AddIndex(
            model_name='resourceinventorytransaction',
            index=models.Index(fields=['resource', 'transaction_type'], name='resource_in_resourc_f05a35_idx'),
        ),
        migrations.AddIndex(
            model_name='resourceinventorytransaction',
            index=models.Index(fields=['created_at'], name='resource_in_created_94ebb5_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequeststatushistory',
            index=models.Index(fields=['request'], name='resource_re_request_488d56_idx'),
        ),
        migrations.AddIndex(
            model_name='resourcerequeststatushistory',
            index=models.Index(fields=['new_status', 'changed_at'], name='resource_re_new_sta_374a30_idx'),
        ),
    ]
